### ISSUE TITLE
The plugin requires manual selection of the target language as English.

### ISSUE THREAD

**Issue by upupnoah** [Oooops-404error/bob-plugin-vocabulary.com#1]
### Hello, the plugin is great!!!
However, when it comes to single words, the right-side auto-selection also needs to be changed to English in order to use it. Is it possible for the plugin to have a separate selection for English when the target language is Chinese? Otherwise, I would need to manually click on English as the target language every time.

### Current solution:
I am using OpenAI Translate to work together and have changed the user command to: `translate from $targetLang to Chinese (simplified)`
I'm sorry, but you haven't provided any text for me to translate. Please provide the text you would like me to translate into English

**Comment by upupnoah** [comment]
I modified the code, and now it is working properly 😊

**Comment by upupnoah** [comment]
Done

**Comment by Oops418** [comment]
Thank you, the code has been merged
